server:
  port: 8888

eureka:
  instance:
    hostname: 172.16.30.63
    prefer-ip-address: true
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}
  client:
    service-url:
      defaultZone: http://user:${REGISTRY_SERVER_PASSWORD:password}@172.16.30.63:8761/eureka/

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/PassionDs/spring-boot-cloud-1
          search-paths: config-repo
  rabbitmq:
    host: 172.16.30.241

security:
  user:
    name: user
    password: ${CONFIG_SERVER_PASSWORD:password}
